server:
  contextPath: /web-app

zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9991/auth/
      sensitive-headers:
    resource:
      path: /api/**
      url: http://localhost:9992/
      sensitive-headers:

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/web-app/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/web-app/auth/oauth/authorize
      clientId: web-app
      preEstablishedRedirectUri: http://localhost:8080/web-app/login
      registeredRedirectUri: http://localhost:8080/web-app/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwcmvczpq7clBagHALJu7gPRbrQH1RXcsZ/z2+x5XeChL0NlEMX8qZyEAhtvgUojf07h4hYz0cIbmUfltS/GtNToPY7wLJlDvaHBlRUYcI1LhTXb/6dyb+fZ7aG5Ogr/+7QyVTgoAlPKOjOqUxyKpS0BxvueJo65dIrxUo/H0eR7+lr8QUymB9eSq9Gei1asP7jsab3rTPhSVNRyZ8RXk3ZL6YzltRye0EVQlb9zjxjgWUJDAmZDBHq6Bs7E+t5V4lTl1+3ibZF0dWUIX2suWbuoBC76i9wa2i0aKwmHOWJDAGr9iAp+xlepuIYcvqoanotoUE9h4d+FMgdTOYYKulPcPBTpWQRNabCl2C74Vxe055AyFz/SXSohNi4W5UMGnlK4yTpP07WmJE/MGXPiPdvhjijNepax8Scaz0dpDd1GY7HQxJarcswq4oqji+DJOQDOSF/bfDQBgxbffzcWJpaCuqXrRjr8xxtumyKjQ+vkGZCI/LCiJE6NT3XcZCzG00Dxw+Cqy512JAe2sNHNMWtQPvxYQDZ31WXaHGX5OtpIndHzsR/6u/KZ7DJOFGsPwIY3d0UnxQ0jJLI22liavXV6VW/MyDkag5LRERufnSTiv0j7uH52lUlBAGtpONwrq4GIlwIeeuVn1hyXr7yfnuh6IaWM6+b9gOZu2fVwj3LcCAwEAAQ==
          -----END PUBLIC KEY-----