server:
  contextPath: /web-app

zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9991/auth/
      sensitive-headers:
    resource:
      path: /api/**
      url: http://localhost:9992/
      sensitive-headers:

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/web-app/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/web-app/auth/oauth/authorize
      clientId: web-app
      preEstablishedRedirectUri: http://localhost:8080/web-app/login
      registeredRedirectUri: http://localhost:8080/web-app/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----