server:
  port: 9991
  contextPath: /auth

security:
  user:
    password: password
  sessions: if-required
  
  # Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: erp
    password: VersacomErp123!
    driver-class: com.mysql.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
          cache: false
   
logging:
  level:
     org:
       springframework:
         security: DEBUG